
name: Test NPM Caching
on:
  push:
    branches:
    - main
jobs:
  init:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Cache node_modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          /home/runner/.cache/Cypress
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install

  test:
    name: Restore Dependencies and Run Tests
    runs-on: 'ubuntu-latest'
    needs: init
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      id: node-cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          /home/runner/.cache/Cypress
        key: node-modules-${{ hashFiles('package-lock.json') }}
      run: |
        npx cypress run