
name: Test NPM Caching
on:
  push:
    branches:
    - main
jobs:
  npm-cache:
    name: 'NPM cache'
    id: setup
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - if: steps.setup.outputs.cache-hit != 'true'
      run: npm install
    # - run: npm test


    # -539, 28, -396