
name: Test NPM Caching
on:
  push:
    branches:
    - main
jobs:
  npm-cache:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: npm test